---
title: 'Ejemplo, Ejercicio 5, Cap 3, Tarea 3'
author: "Elvira RS "
date: "2025-02-27"
output: html_document
---

##Base de datos

```{r}
knitr::opts_chunk$set(echo= TRUE)
library(tidyverse)
```

#Funcion de densidad

```{r}
f_den <- function(x, B = 1) {
  if (x >= -B & x <= 0) {
    y <- 1 / B^2 * x + 1 / B
  } else if (x > 0 & x <= B) {
    y <- -1 / B^2 * x + 1 / B
  } else {
    y <- 0
  }
  return(y)
}

fv_den <- Vectorize(f_den, "x")

f_dis <- function(x, B = 1) {
  if (x < (-1) * B) {
    y <- 0
  } else if (x >= -B & x <= 0) {
    y <- (x + B) * (fv_den(x) / 2)
  } else if (x > 0 & x <= B) {
    y <- 1 - (B - x) * fv_den(x) / 2
  } else {
    y <- 0
  }
  return(y)
}

x <- seq(-1.5, 1.5, length.out = 500)

y <- sapply(x, f_den)

ggplot() +
  geom_line(aes(x, y), color = "pink", size = 1.2) +
  geom_function(fun = fv_den, color = "green", size = 1.2) +
  xlim(-1.5, 1.5) +
  theme_bw()

```
#Probabilidad de densidad
```{r}
decision <- function(Vj, Vi, B=1){
  Vji <- Vj-Vi
  PVji <- f_dis(Vji)
  sub_text <- paste0("Utilidades observadas Vj=", Vj, "Vi=", Vi, "Vj-Vi=", Vji, collapse = )
  
  ggplot() +
    geom_function(fun = fv_den, color = "brown", linewidth = 0.5, xlim = c(-B - 0.1, B + 0.1)) +
    stat_function(fun = fv_den, geom = "area", fill = "goldenrod3", alpha = 0.5, xlim = c(-B, Vji)) +
    geom_text(aes(B/2, 1/(2*B), label = paste0("Prob(Vj)=", round(PVji, 2), sep=""))) +
    labs(title = "Probabilidad de elección") +
    theme_bw()
}

decision(Vj = 6, Vi = 5.5)
```

#Complemento de función de densidad
```{r}
decision_complemento <- function(Vj, Vi, B = 1) {
  Vji <- Vj - Vi
  PVji <- f_dis(Vji)
  PVji_complemento <- 1 - PVji
  sub_text <- paste0("Vj = ", Vj, ", Vi = ", Vi, ", Vj-Vi = ", Vji)
  
  ggplot() +
    geom_function(fun = fv_den, 
                 color = "gray30", 
                 linewidth = 0.6,
                 xlim = c(-B - 0.1, B + 0.1)) +
    
    
    stat_function(fun = fv_den,
                 geom = "area",
                 fill = "darkgreen",
                 alpha = 0.3,
                 xlim = c(Vji, B)) +
   
    #geom_vline(xintercept = Vji, 
              #linetype = "dashed", 
              #color = "red",
              #linewidth = 0.5) +
    
    geom_label(aes(x = -B/2, y = 1/(2*B), 
                  label = paste0("P(Vj) = ", round(PVji, 2))),
              fill = "goldenrod1",
              color = "white") +
    geom_label(aes(x = B/2, y = 1/(2*B), 
                  label = paste0("P(No Vj) = ", round(PVji_complemento, 2))),
              fill = "darkgreen",
              color = "white") +
    labs(title = "Complemento de la probabilidad",
        subtitle = sub_text,
        x = "B/2",
        y = "1/(2*B)") +
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5),
         plot.subtitle = element_text(hjust = 0.5))
}

decision_complemento(Vj = 6, Vi = 5.5)

```




